import { ArenaBlock, ConnectionData } from 'arena-ts'

export const dummyBlockData: ArenaBlock & ConnectionData = {
  id: 123456,
  title: '',
  updated_at: Date.now().toString(),
  created_at: Date.now().toString(),
  state: 'processing',
  comment_count: 0,
  generated_title: '',
  content_html: '',
  description_html: '',
  visibility: undefined,
  content: '',
  description: '',
  source: null,
  image: null,
  embed: null,
  attachment: null,
  metadata: null,
  base_class: 'Block',
  class: 'Image',
  user: {
    id: 123456,
    created_at: '2019-08-24T18:18:20.261Z',
    slug: 'jaza-syed',
    username: 'Jaza Syed',
    first_name: 'Jaza',
    last_name: 'Syed',
    full_name: 'Jaza Syed',
    avatar: '',
    avatar_image: null,
    channel_count: 0,
    following_count: 0,
    profile_id: 123456,
    follower_count: 0,
    initials: 'DB',
    can_index: false,
    metadata: {
      description: null
    },
    is_premium: true,
    is_lifetime_premium: false,
    is_supporter: false,
    is_exceeding_connections_limit: false,
    is_confirmed: true,
    is_pending_reconfirmation: false,
    is_pending_confirmation: false,
    badge: 'premium',
    base_class: 'User',
    class: 'User'
  },
  position: 0,
  selected: false,
  connection_id: undefined,
  connected_at: Date.now().toString(),
  connected_by_user_id: 123456,
  connected_by_username: undefined,
  connected_by_user_slug: undefined
}
